### ISSUE TITLE
Add `CircuitConfig` option to `compile` function

### ISSUE THREAD

**Issue by cryptograph** [erhant/circomkit#28]
Currently,  `compile` https://github.com/erhant/circomkit/blob/main/src/circomkit.ts#L201 uses `instantiate` https://github.com/erhant/circomkit/blob/main/src/circomkit.ts#L204 without `CircuitConfig` provided so it is always looking for `circuits.json` for the configuration. That makes harder to use it for more than 1 circuit.

**Comment by erhant** [comment]
Ah good point, wonder why I left it like that. I will add an optional parameter for `compile` for the `CircuitConfig`.

The CLI will still check for `circuits.json`, but you shall be able to pass the config from within the code.

Thanks for pointing out!

**Comment by erhant** [comment]
I have a PR for this but I gotta do a bit tidying to it, I will publish soon.

**Comment by erhant** [comment]
Done! Published with `v0.0.17`

Also here is a 🍪  as a thanks, this was my first issue by someone to my first ever package hahah
