### ISSUE TITLE
feat: Allow to generate the C witness calculator on compilation

### ISSUE THREAD

**Issue by ctrlc03** [erhant/circomkit#43]
Currently, when compiling a circuit, it is not possible to generate the C witness calculator files. By adding a optional config entry, we can decide whether to generate those files or not. 

Would you be happy to have this feature in?

ps. great work with `circomkit`, we are just now integrating it in [maci](https://github.com/privacy-scaling-explorations/maci), and having this option would make it much easier for us to integrate it in our workflows.

**Comment by erhant** [comment]
Sounds great; saw your PR, merging in a moment then I will release as v0.0.20.

Awesome to hear that MACI is using it, thanks! ❤️

**Comment by erhant** [comment]
milady https://github.com/erhant/circomkit/releases/tag/v0.0.20

**Comment by ctrlc03** [comment]
> milady https://github.com/erhant/circomkit/releases/tag/v0.0.20

You're a star, thank you!! Please let me know if there's anything I can help with, would love to contribute to circomkit

**Comment by erhant** [comment]
> You're a star, thank you!! Please let me know if there's anything I can help with, would love to contribute to circomkit

Thanks a lot! :)

I will do a deep dive to this code again soon, its been a while, but I basically want more capabilities over the symbols (e.g. `editWitness` function) and need much more testing there, for many components & multi-dim arrays and such.

I will create an issue with `help wanted` tag when the time comes 🥂

**Comment by ctrlc03** [comment]
> and need much

Sounds great, looking forward to that, and keep up the good work 🚀
