### ISSUE TITLE
circomkit:setup

### ISSUE THREAD

**Issue by ctrlc03** [erhant/circomkit#50]
I was wondering if it's completely necessary to perform this step? https://github.com/erhant/circomkit/blob/main/src/circomkit.ts#L417 

The ptau(s) that circomkit downloads are from the Hermez phase1 ceremony, which are ready to be used in a phase2 ceremony. 

ps. the [base url](https://github.com/erhant/circomkit/blob/main/src/utils/ptau.ts#L5) of the ptau files should be updated just to be safe  - seems like they have moved to [google storage](https://github.com/iden3/snarkjs/blob/master/README.md?plain=1#L175-L195) 

EDIT: issue breakdown

- [x] Remove [these lines](https://github.com/erhant/circomkit/blob/main/src/circomkit.ts#L414-L417) and use existing PTAU instead of thats being created ptau2init there
- [x] Update base URL for Perpetual Powers of Tau urls
- [x] Add an extract function that looks for the zKey (w.r.t circuit name and configured protocol) and generates the vKey
- [x] Add CLI wrapper that calls extract
- [x] No need to check if PTAUs for larger constrain counts exist as you mentioned above, but maybe we can add a comment TODO: check for performance gains when larger PTAUs are found instead of the target PTAU; I want to check that out sometime :)

**Comment by ctrlc03** [comment]
> Huh yeah that makes sense actually.
> 
> Does using the same PTAU for both phases have security implications though? We could maybe add an option to skip that part in config during tests, or automatically skip that part if `NODE_ENV == 'test'`, wdyt?
> 
> > ps. the [base url](https://github.com/erhant/circomkit/blob/main/src/utils/ptau.ts#L5) of the ptau files should be updated just to be safe - seems like they have moved to [google storage](https://github.com/iden3/snarkjs/blob/master/README.md?plain=1#L175-L195)
> > ah yeah indeed, I will add those with this issue's fix!
> 
> Also I saw on Iden3 telegram that someone said you can use higher PTAUs for lower constraints, and it does not incur any performance issues regarding the output size. I will quote his message here:
> 
> > I have a circuit with ~50k constraints. I previously used PTAU_20 (up to 1MM constraints) which resulted in a zky that was 21.5 MB. I tried it again with PTAU_16 (max 64k constraints) and it also resulted in a 21.5MB file. I forgot to benchmark the time it took to generate but thought I could ask here: is there any difference in using PTAUs that are larger than necessary for generating zkey, wasm or verification keys? Does it take longer with bigger ones? It seems like the outcome file is the same size, are there any other differences?
> 
> If this is indeed the case, we can also slightly change the `ptau` function, which currently checks specifically for the smallest PTAU ([here](https://github.com/erhant/circomkit/blob/main/src/circomkit.ts#L186)). It could indeed check if a PTAU larger exists as well.
> 
> Looking forward to hear your ideas before starting on this 🙏🏻

Thanks for your quick response :)

Well ideally one would not have to redo a phase1, so I image circomkit being used to bootstrap a groth16 phase2 (for testing purposes mostly as single contribution zkeys should never be used in prod) and for generating a plonk/fflonk zkey, and thus we can directly download a ptau which fits the constraints of the circuit. These ones that circomkit uses, and other tools for ceremonies like [p0tion](https://github.com/privacy-scaling-explorations/p0tion), are ready for phase2. TLDR I think it can be safely removed as you'd want people to re-use ptau that have undergone a trusted setup (for both simplicity and safety).

With regards to checking for the largest one, I'm not entirely sure, though I would assume as well that it works that way (you can use a larger one with no problems). Though I've always seen projects download the smallest that fit (probably to simplify the logic). Same in [p0tion](https://github.com/privacy-scaling-explorations/p0tion/blob/dev/packages/phase2cli/src/commands/setup.ts#L279) we always download the smallest and do not bother checking if a larger one is present. Imo you could easily keep it the way it is, and to save space for users, you could add an option to cleanup afterwards. 

Lmk if I can be of any help, happy to submit a PR for it as well 😃

**Comment by erhant** [comment]
Thanks for your detailed explanations 🙏🏻 . I didn't quite understand what is to be done here though (quite a sleep day today), I would love if you could have a PR for this (the setup part in particular)!

My question marks are due to the following:
- Circomkit doesn't do phase-1 setup at all, and during phase-2 setup it asks for a PTAU to given explicitly if the prime is not `bn128` since it cant download a PTAU automatically in that case. So this is already how we want it to be I think.
- Setup is not mandatory too, and will only run if you don't have keys; perhaps key generation could be a different function like `keygen` both in CLI and the API so that if one has phase-2 output already they can simply generate the keys. Is this what we should do here?

**Comment by ctrlc03** [comment]
> Thanks for your detailed explanations 🙏🏻 . I didn't quite understand what is to be done here though (quite a sleep day today), I would love if you could have a PR for this (the setup part in particular)!

> My question marks are due to the following:

> Circomkit doesn't do phase-1 setup at all, and during phase-2 setup it asks for a PTAU to given explicitly if the prime is not bn128 since it cant download a PTAU automatically in that case. So this is already how we want it to be I think.
Setup is not mandatory too, and will only run if you don't have keys; perhaps key generation could be a different function like keygen both in CLI and the API so that if one has phase-2 output already they can simply generate the keys. Is this what we should do here?

Definitely, I'd be happy to do that.

1: Correct.
2: The phase2 "output" is actually the proving key (and the verifying key which can be extracted at any time) - I would imagine some scenarios of devs using circomkit as follows:

* someone has already a zKey (in circomkit this is named pKey) and also they already have a vKey, they come to generate proofs (zKey needed) and verify them (vKey needed) by passing the local path to these artifacts
* someone does not have a zKey and needs one which they can use for dev purposes and testing - we generate it from scratch using [this](https://github.com/erhant/circomkit/blob/main/src/circomkit.ts#L421) and extract the vKey which they can use for verification
* someone has a zKey but does not have a vKey extracted, and wants to verify a proof. We can directly [extract](https://github.com/iden3/snarkjs/blob/master/src/zkey_export_verificationkey.js#L28) the vKey from the zKey (so here one could add an option to specify a zKey path in [`verify`](https://github.com/erhant/circomkit/blob/main/src/circomkit.ts#L459)

So in terms of what could be done here is to remove this `preparePhase2` and just use `newZkey`. And maybe allow to specify a zKey path when verifying a proof and extracting the vKey from there.

Lmk if that makes sense

**Comment by ctrlc03** [comment]
> too much stuff in your hands already lemme know I

Soun

> > So in terms of what could be done here is to remove this preparePhase2 and just use newZkey. And maybe allow to specify a zKey path when verifying a proof and extracting the vKey from there.
> 
> Ahh that makes so much sense, sounds good to me!
> 
> Just one thing:
> 
> > someone has a zKey but does not have a vKey extracted, and wants to verify a proof. We can directly [extract](https://github.com/iden3/snarkjs/blob/master/src/zkey_export_verificationkey.js#L28) the vKey from the zKey (so here one could add an option to specify a zKey path in [verify](https://github.com/erhant/circomkit/blob/main/src/circomkit.ts#L459)
> 
> For this case, I would much prefer to have a separate method to extract `zKey` instead of an optional arg to `verify`, so that we can also have people extract a vKey if they have a zKey already using the CLI (`npx circomkit extract <circuit-name>`). Within the `verify` function we can have it check for a zKey and do this automatically if a vKey does not exist.
> 
> So the tasks about this issue's respective PR would be:
> 
> * [ ]  Remove [these lines](https://github.com/erhant/circomkit/blob/main/src/circomkit.ts#L414-L417) and use existing PTAU instead of thats being created `ptau2init` there
> * [ ]  Update base URL for Perpetual Powers of Tau urls
> * [ ]  Add an `extract` function that looks for the `zKey` (w.r.t circuit name and configured protocol) and generates the `vKey`
> * [ ]  Add CLI wrapper that calls `extract`
> * [ ]  No need to check if PTAUs for larger constrain counts exist as you mentioned above, but maybe we can add a comment `TODO: check for performance gains when larger PTAUs are found instead of the target PTAU`; I want to check that out sometime :)
> 
> If I am correct about these & it suits you as well, its good to go! If you have too much stuff in your hands already lemme know I can also work on this one 👍🏻

Sounds like a good plan 🚀 I'll knock it off this week
