### ISSUE TITLE
Print info about zKey

### ISSUE THREAD

**Issue by erhant** [erhant/circomkit#58]
For example, we can see how many signals are expected there.

**Comment by 0xjei** [comment]
Some time ago I wrote a simple and optimized utility [getR1CSInfo()](https://github.com/privacy-scaling-explorations/p0tion/blob/0fb27d7e49d4e2e119c302801d828424347b581b/packages/actions/src/helpers/utils.ts#L413) for p0tion to read the info from R1CS files without fully processing them. This avoids hitting the heap size limits of NodeJS for very large R1CS and avoid people to hang for getting the results. 

May I can work on this? I think that would be worth it! Let me know! @erhant

**Comment by erhant** [comment]
By the way, I wanted to implement  performant file-reader for the `.sym` file as well. 

Loading the entire symbols file as an object may be heavy when the circuit is large; and note that `getConstraintCount` simply reads the number of keys in that object so we should definitely find a more efficient way to do that.

The actual feature that I want to implement is a `query` function, which queries symbols! For example:

```ts
// for WitnessTester
await circuit.query("out");
// should return an object with witness values
{
  "main.out": 5,
  "main.component.out": [6, 7, 8]
}
```

applies to Circomkit as well

```sh
# circomkit.query(circuit, input, pattern);
$ npx circomkit query myCircuit myInput out
{
  "main.out": 5,
  "main.component.out": [6, 7, 8]
}
```

I want to explore what I can do with this kind of query function. For example `editWitness` does a lot of symbol juggling inside and it could instead use this query functionality within. Basically a debugging tool for the witness, or a mean of reading & writing symbol values.

In the end, I need an efficient `.sym` file reader for this thing^

**Comment by 0xjei** [comment]
Thanks @erhant for the explanation.

If you need to search for specific patterns or keys within a `.sym` file without loading the whole file in-memory, I think a script that reads the file line by line should be fine (stream approach - should be more efficient for large files).

This script should have a query function for symbols, e.g. search for the symbol 'out' and return all related symbols and their witness values (as you've mentioned above). Then, we just need a way to associate the found symbols with their corresponding witness values.

What are your thoughts about? Let me know, I will be happy to work on it.

**Comment by 0xjei** [comment]
> If streaming is the way-to-go for `.sym`, I would like to work on that on a separate issue; because I also want to write some more tests for edge-cases (nested arrays, duplicate signals names and whatnot).

Agree, makes sense.

> For now, lets continue with the fast zkey && / || r1cs reader if thats alright with you 🙏🏻

Yup. One thing that is not clear to me is that, if I am not mistaken, the `r1cs`nmè gives us all this information. What else do you want to get from the `zkey`?

```bash
npx snarkjs r1cs info multiplier_3.r1cs

[INFO]  snarkJS: Curve: bn-128
[INFO]  snarkJS: # of Wires: 12
[INFO]  snarkJS: # of Constraints: 8
[INFO]  snarkJS: # of Private Inputs: 3
[INFO]  snarkJS: # of Public Inputs: 0
[INFO]  snarkJS: # of Labels: 16
[INFO]  snarkJS: # of Outputs: 1
```
 
> > Then, we just need a way to associate the found symbols with their corresponding witness values.
> 
> WitnessTester is doing this already, I just need to refactor it to work with the to-be-written `query` function! :) We can use the `varIdx` of a symbol to access the value as `witness[varIdx]`, which is one of the numbers in that line that is comma-separated. If the witness file is too large, another efficient file-reader is needed on that too.

Sweet, sounds good! Do you know the meaning of of the values in the `.sym` per each row? Like below, what's the meaning of the `1`s?

```bash
1,1,1,main.out
```

Okay, I think that writing the line-by-line stream reader should be fast enough. Then, we just need to incorporate the refactored `WitnessTester`.

**Comment by erhant** [comment]
> One thing that is not clear to me is that, if I am not mistaken, the r1csnmè gives us all this information. What else do you want to get from the zkey?

Ah yes, I think that is correct. I had opened this issue during a zkCTF last weekend hahah; R1CS does the trick for us 👌🏻

---

> Like below, what's the meaning of the 1s?
> 
> ```txt
> 1,1,1,main.out
> ```

Based on the [loadSymbols function of circom_tester](https://github.com/iden3/circom_tester/blob/main/wasm/tester.js#L116) we split this comma-separated values into `arr` of length 4, where:

- `arr[0]`: label index (1)
- `arr[1]`: variable index (1)
- `arr[2]`: component index (1)
- `arr[3]`: symbol name (`main.out`)

I still have to understand what label index and component index means, but I am certain that variable index is the index within the `bigint[]` array of the witness, i.e. `witness[1]` has the value of `main.out` here.

In WitnessTester, I actually count the number of `.`s in the symbol name to see if the symbol is within the main or not hahah, but there should be a much better way certainly.

**Comment by 0xjei** [comment]
> > One thing that is not clear to me is that, if I am not mistaken, the r1csnmè gives us all this information. What else do you want to get from the zkey?
> 
> Ah yes, I think that is correct. I had opened this issue during a zkCTF last weekend hahah; R1CS does the trick for us 👌🏻

Sounds good then :blush: 

> 
> > Like below, what's the meaning of the 1s?
> > ```
> > 1,1,1,main.out
> > ```
> 
> Based on the [loadSymbols function of circom_tester](https://github.com/iden3/circom_tester/blob/main/wasm/tester.js#L116) we split this comma-separated values into `arr` of length 4, where:
> 
> * `arr[0]`: label index (1)
> * `arr[1]`: variable index (1)
> * `arr[2]`: component index (1)
> * `arr[3]`: symbol name (`main.out`)
> 
> I still have to understand what label index and component index means, but I am certain that variable index is the index within the `bigint[]` array of the witness, i.e. `witness[1]` has the value of `main.out` here.

That's good to know, thank you for the references and explanation :pray: 
 
> In WitnessTester, I actually count the number of `.`s in the symbol name to see if the symbol is within the main or not hahah, but there should be a much better way certainly.

Hmm if I take the `.sym` of `multiplier_3`, I see something like below. What do you do to recognise if a symbol is within the main or not?

```bash
1,1,1,main.out
2,2,1,main.in[0]
3,3,1,main.in[1]
4,4,1,main.in[2]
5,5,1,main.inner[0]
6,-1,1,main.inner[1]
7,-1,0,main.isZero[0].out
8,6,0,main.isZero[0].in
9,7,0,main.isZero[0].inv
10,-1,0,main.isZero[1].out
11,8,0,main.isZero[1].in
12,9,0,main.isZero[1].inv
13,-1,0,main.isZero[2].out
14,10,0,main.isZero[2].in
15,11,0,main.isZero[2].inv
```

**Comment by erhant** [comment]
Those with only 1 `.` character within them are symbols of the `main` component, in this case:

```c
1,1,1,main.out
2,2,1,main.in[0]
3,3,1,main.in[1]
4,4,1,main.in[2]
5,5,1,main.inner[0]
6,-1,1,main.inner[1]
```

Some more details about this stuff:

- `arr[0]` (label index) is always equal to the line number within the symbol file (still havent seen a counterexample on this) 
- `arr[1]` (variable index) sometimes has `-1`s, that just means that the corresponding symbol has been "optimized"; to see that in action you can compile multiplier_3 with `optimization: 0` and you will have no -1s in the symbol file. the more you optimize, the more -1s you will have
- `arr[2]` (component index) seems to be largest for the main component, and goes to 0 at the deepest component

**Comment by 0xjei** [comment]
> Those with only 1 `.` character within them are symbols of the `main` component, in this case:
> 
> ```c
> 1,1,1,main.out
> 2,2,1,main.in[0]
> 3,3,1,main.in[1]
> 4,4,1,main.in[2]
> 5,5,1,main.inner[0]
> 6,-1,1,main.inner[1]
> ```
> 
> Some more details about this stuff:
> 
> * `arr[0]` (label index) is always equal to the line number within the symbol file (still havent seen a counterexample on this)
> * `arr[1]` (variable index) sometimes has `-1`s, that just means that the corresponding symbol has been "optimized"; to see that in action you can compile multiplier_3 with `optimization: 0` and you will have no -1s in the symbol file. the more you optimize, the more -1s you will have
> * `arr[2]` (component index) seems to be largest for the main component, and goes to 0 at the deepest component

Sweet, thank you so much. Now these lines make a lot more sense :cloud:

**Comment by 0xjei** [comment]
Hello @erhant, I noticed the `info()` method [here](https://github.com/erhant/circomkit/blob/0af1603b31f5b0c009b06e2b580fda5a9c657a28/src/circomkit.ts#L177) which prints the `r1cs` information using `snarkjs`. 

Should I consider this issue closed?

**Comment by erhant** [comment]
yo! you are right actually, but I kept this open as I believe you r1cs reader used in p0tion is much superior to that of snarkjs's;
I would like to take a look at that reader in any case, so I think I will keep this open for a bit while & also assigning myself 🙏🏻 

I will let you know!

**Comment by 0xjei** [comment]
> yo! you are right actually, but I kept this open as I believe you r1cs reader used in p0tion is much superior to that of snarkjs's; I would like to take a look at that reader in any case, so I think I will keep this open for a bit while & also assigning myself 🙏🏻
> 
> I will let you know!

Oh, don't worry! I can try updating my reader to return all the necessary information as I see in your code :)

**Comment by erhant** [comment]
ah that would be perfect actually 🎈
