### ISSUE TITLE
Some functions do not exit on completion

### ISSUE THREAD

**Issue by ScreamingHawk** [erhant/circomkit#95]
I haven't done a complete pass but I noticed the following commands don't exit on completion. I have to kill the process. 

```sh
npx circomkit setup <circuit>
npx circomkit prove <circuit> <input>
npx circomkit verify <circuit> <input>
npx circomkit contract <circuit>
```

`compile`, `info` and `calldata` all appear to return correctly.

**Comment by erhant** [comment]
Closed with #96
