### ISSUE TITLE
bug:  LinkError: WebAssembly.instantiate(): Import #4 module="runtime" function="printDebug" error: function import requires a callable

### ISSUE THREAD

**Issue by erhant** [erhant/circomkit#98]
See fail here: https://github.com/semaphore-protocol/semaphore/actions/runs/11344147674/job/31548268406

**Comment by numtel** [comment]
This is actually what I see as a snarkjs bug that occurs with the new Circom 2.2.0

In that build, the "setup Circom" step uses the latest Circom version binary available.

I fixed this last night on circuitscan by copying (and changing commonjs to module export syntax) the witness_calculator.js from a circom 2.2.0 build output. It works for circom 2.2.0 as well as earlier versions

https://github.com/circuitscan/circuitscan/commit/1e554e3b5ce8904f7e34a4d62b80ae29eb5765f3

**Comment by numtel** [comment]
Regarding circom 2.2.0 and their decision to change the default optimization to 1... :rofl: so much for my recent PR...

I'm considering making another PR that just omits optimization argument if it's not specified in the circomkit.json so it goes with whatever is default on the compiler.

**Comment by erhant** [comment]
> This is actually what I see as a snarkjs bug that occurs with the new Circom 2.2.0

ohhh, thank you for this info! had no idea what was the bug so far... People using snarkjs should have failures all around on this then, right?

> Regarding circom 2.2.0 and their decision to change the default optimization to 1... 🤣 so much for my recent PR...
>
> I'm considering making another PR that just omits optimization argument if it's not specified in the circomkit.json so it goes with whatever is default on the compiler.

I think this is the correct approach for this as well.

**Comment by numtel** [comment]
> ohhh, thank you for this info! had no idea what was the bug so far... People using snarkjs should have failures all around on this then, right?

I believe so, I'll check through it later and submit an issue/PR on snarkjs.

**Comment by erhant** [comment]
Here is a related issue: https://github.com/iden3/circom/issues/308

kudos to @cedoor

**Comment by numtel** [comment]
> Here is a related issue: [iden3/circom#308](https://github.com/iden3/circom/issues/308)
> 
> kudos to @cedoor

Ah ok, replied there. It looks like the fix is already waiting to be merged: https://github.com/iden3/circom_runtime/pull/117

Snarkjs was also already awaiting a PR for bumping that dependency to the latest version, it will have to be bumped further. https://github.com/iden3/snarkjs/pull/526

**Comment by OBrezhniev** [comment]
Hi @erhant @numtel ! We've just released [snarkjs v0.7.5](https://github.com/iden3/snarkjs/releases/tag/v0.7.5) with the fix.

**Comment by erhant** [comment]
Thank you for the notice!
